---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ingress-nginx
    repoURL: https://github.com/Myafq/gitops-example-prod-system.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}